#include <stdlib.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>

#include "htmlent.h"
#include "mem.h"
#include "strbuf.h"

static const struct {
  char *ent;
  char *dec;
} htmlent_table[] = {
  /* this table was generated by ../res/htmlent_table.php, see make.php */
  /* http://migo.sixbit.org/more/html-entities.html */
# include "../res/htmlent_table.gen"
  
  /* end */
  { NULL, NULL }
};

static const char *
htmlent_table_lookup_dec(char *ent) 
{
  size_t i = 0;
  
  for (; htmlent_table[i].ent != NULL; ++i)
    if (strcmp(ent, htmlent_table[i].ent) == 0)
      return (const char*) htmlent_table[i].dec;
  
  return NULL;
}

/* ---------------------------------------- */

char *
htmlent_decode(const char *html)
{
  bool in_ent = false;
  struct strbuf *buf = strbuf_init();
  struct strbuf *ent = strbuf_init();
  char *res;
  const char *dec;
  
  while (*html) {
    char c = *html++;
    
    if (in_ent) {
      strbuf_addc(ent, c);
      
      if (c == ';') {
        char *ent_cstr = strbuf_cstr(ent);
        strbuf_clear(ent);
        
        in_ent = false;
        dec = htmlent_table_lookup_dec(ent_cstr);
        amz_free(ent_cstr);
        
        if (dec != NULL)
          strbuf_add(buf, dec);
      }
      
      continue;
    } else if (c == '&') {
      in_ent = true;
      strbuf_addc(ent, c);
      continue;
    }
    
    strbuf_addc(buf, c);
  }
  
  res = strbuf_cstr(buf);
  strbuf_free(buf);
  strbuf_free(ent);
  
  return res;
}
